# Generated by Django 4.1 on 2022-12-10 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_trx_calculation_strike_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trx_calculation',
            name='partition_of_time',
            field=models.DecimalField(db_column='PARTITION_OF_TIME', decimal_places=4, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trx_calculation',
            name='date_simulate',
            field=models.DateTimeField(db_column='DATE_SIMULATE', default=datetime.datetime(2022, 12, 10, 16, 41, 8, 636970)),
        ),
        migrations.AlterField(
            model_name='trx_calculation',
            name='interest_rate',
            field=models.DecimalField(db_column='INTEREST_RATE', decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trx_calculation',
            name='stock_price',
            field=models.DecimalField(db_column='STOCK_PRICE', decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trx_calculation',
            name='strike_price',
            field=models.DecimalField(db_column='STRIKE_PRICE', decimal_places=4, max_digits=20),
        ),
    ]
