# Generated by Django 4.1 on 2022-12-10 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0003_trx_calculation_partition_of_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trx_calculation',
            name='return_expectation',
            field=models.DecimalField(db_column='RETURN_EXPECTATION', decimal_places=4, default=-0.004619266, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trx_calculation',
            name='date_simulate',
            field=models.DateTimeField(db_column='DATE_SIMULATE', default=datetime.datetime(2022, 12, 10, 17, 44, 46, 46983)),
        ),
    ]
