# Generated by Django 4.1 on 2023-03-13 14:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='master_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URI_link', models.CharField(db_column='URI_LINK', max_length=500)),
                ('date_created', models.DateField(blank=True, db_column='DATE_CREATED', default=datetime.date.today)),
            ],
            options={
                'db_table': 'BBCSCRAP_MASTERLINK',
            },
        ),
        migrations.CreateModel(
            name='detail_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='TITLE', max_length=1000)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=10000)),
                ('date_created', models.DateField(blank=True, db_column='DATE_CREATED', default=django.utils.timezone.now)),
                ('link_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bbcscrap.master_link')),
            ],
            options={
                'db_table': 'BBCSCRAP_DETAILLINK',
            },
        ),
    ]
