# Generated by Django 4.1 on 2023-03-13 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbcscrap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_link',
            name='link_id',
            field=models.ForeignKey(db_column='LINK_ID', on_delete=django.db.models.deletion.RESTRICT, to='bbcscrap.master_link'),
        ),
    ]
