# Generated by Django 4.1 on 2023-03-13 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bbcscrap', '0002_alter_detail_link_link_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_link',
            name='date_created',
            field=models.DateField(blank=True, db_column='DATE_CREATED', default=django.utils.timezone.now),
        ),
    ]
