# Generated by Django 4.1 on 2023-03-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbcscrap', '0005_alter_detail_link_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_link',
            name='date_created',
            field=models.DateTimeField(blank=True, db_column='DATE_CREATED', default='2023-03-16 10:08:50'),
        ),
        migrations.AlterField(
            model_name='master_link',
            name='date_created',
            field=models.DateTimeField(blank=True, db_column='DATE_CREATED', default='2023-03-16 10:08:50'),
        ),
    ]
